"""message_channels create address column

Revision ID: e5936aeabbfa
Revises: a81d9e8ea1ab
Create Date: 2020-05-29 13:31:10.437442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5936aeabbfa'
down_revision = 'a81d9e8ea1ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_channels', sa.Column('address', sa.String()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_channels', 'address')
    # ### end Alembic commands ###
